/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskRouteImport } from './routes/ask'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as DuasRouteImport } from './routes/duas'
import { Route as HadithRouteImport } from './routes/hadith'
import { Route as HajjRouteImport } from './routes/hajj'
import { Route as NamesRouteImport } from './routes/names'
import { Route as PillarsRouteImport } from './routes/pillars'
import { Route as PrayerTimesRouteImport } from './routes/prayer-times'
import { Route as QiblaRouteImport } from './routes/qibla'
import { Route as QuranRouteImport } from './routes/quran'
import { Route as QuranNumberRouteImport } from './routes/quran.$number'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DuasRoute = DuasRouteImport.update({
  id: '/duas',
  path: '/duas',
  getParentRoute: () => rootRouteImport,
} as any)
const HadithRoute = HadithRouteImport.update({
  id: '/hadith',
  path: '/hadith',
  getParentRoute: () => rootRouteImport,
} as any)
const HajjRoute = HajjRouteImport.update({
  id: '/hajj',
  path: '/hajj',
  getParentRoute: () => rootRouteImport,
} as any)
const NamesRoute = NamesRouteImport.update({
  id: '/names',
  path: '/names',
  getParentRoute: () => rootRouteImport,
} as any)
const PillarsRoute = PillarsRouteImport.update({
  id: '/pillars',
  path: '/pillars',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerTimesRoute = PrayerTimesRouteImport.update({
  id: '/prayer-times',
  path: '/prayer-times',
  getParentRoute: () => rootRouteImport,
} as any)
const QiblaRoute = QiblaRouteImport.update({
  id: '/qibla',
  path: '/qibla',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranRoute = QuranRouteImport.update({
  id: '/quran',
  path: '/quran',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranNumberRoute = QuranNumberRouteImport.update({
  id: '/$number',
  path: '/$number',
  getParentRoute: () => QuranRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/calendar': typeof CalendarRoute
  '/duas': typeof DuasRoute
  '/hadith': typeof HadithRoute
  '/hajj': typeof HajjRoute
  '/names': typeof NamesRoute
  '/pillars': typeof PillarsRoute
  '/prayer-times': typeof PrayerTimesRoute
  '/qibla': typeof QiblaRoute
  '/quran': typeof QuranRouteWithChildren
  '/quran/$number': typeof QuranNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/calendar': typeof CalendarRoute
  '/duas': typeof DuasRoute
  '/hadith': typeof HadithRoute
  '/hajj': typeof HajjRoute
  '/names': typeof NamesRoute
  '/pillars': typeof PillarsRoute
  '/prayer-times': typeof PrayerTimesRoute
  '/qibla': typeof QiblaRoute
  '/quran': typeof QuranRouteWithChildren
  '/quran/$number': typeof QuranNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/calendar': typeof CalendarRoute
  '/duas': typeof DuasRoute
  '/hadith': typeof HadithRoute
  '/hajj': typeof HajjRoute
  '/names': typeof NamesRoute
  '/pillars': typeof PillarsRoute
  '/prayer-times': typeof PrayerTimesRoute
  '/qibla': typeof QiblaRoute
  '/quran': typeof QuranRouteWithChildren
  '/quran/$number': typeof QuranNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/calendar'
    | '/duas'
    | '/hadith'
    | '/hajj'
    | '/names'
    | '/pillars'
    | '/prayer-times'
    | '/qibla'
    | '/quran'
    | '/quran/$number'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/calendar'
    | '/duas'
    | '/hadith'
    | '/hajj'
    | '/names'
    | '/pillars'
    | '/prayer-times'
    | '/qibla'
    | '/quran'
    | '/quran/$number'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/calendar'
    | '/duas'
    | '/hadith'
    | '/hajj'
    | '/names'
    | '/pillars'
    | '/prayer-times'
    | '/qibla'
    | '/quran'
    | '/quran/$number'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  CalendarRoute: typeof CalendarRoute
  DuasRoute: typeof DuasRoute
  HadithRoute: typeof HadithRoute
  HajjRoute: typeof HajjRoute
  NamesRoute: typeof NamesRoute
  PillarsRoute: typeof PillarsRoute
  PrayerTimesRoute: typeof PrayerTimesRoute
  QiblaRoute: typeof QiblaRoute
  QuranRoute: typeof QuranRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duas': {
      id: '/duas'
      path: '/duas'
      fullPath: '/duas'
      preLoaderRoute: typeof DuasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hadith': {
      id: '/hadith'
      path: '/hadith'
      fullPath: '/hadith'
      preLoaderRoute: typeof HadithRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hajj': {
      id: '/hajj'
      path: '/hajj'
      fullPath: '/hajj'
      preLoaderRoute: typeof HajjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/names': {
      id: '/names'
      path: '/names'
      fullPath: '/names'
      preLoaderRoute: typeof NamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pillars': {
      id: '/pillars'
      path: '/pillars'
      fullPath: '/pillars'
      preLoaderRoute: typeof PillarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer-times': {
      id: '/prayer-times'
      path: '/prayer-times'
      fullPath: '/prayer-times'
      preLoaderRoute: typeof PrayerTimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qibla': {
      id: '/qibla'
      path: '/qibla'
      fullPath: '/qibla'
      preLoaderRoute: typeof QiblaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran': {
      id: '/quran'
      path: '/quran'
      fullPath: '/quran'
      preLoaderRoute: typeof QuranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran/$number': {
      id: '/quran/$number'
      path: '/$number'
      fullPath: '/quran/$number'
      preLoaderRoute: typeof QuranNumberRouteImport
      parentRoute: typeof QuranRoute
    }
  }
}

interface QuranRouteChildren {
  QuranNumberRoute: typeof QuranNumberRoute
}

const QuranRouteChildren: QuranRouteChildren = {
  QuranNumberRoute: QuranNumberRoute,
}

const QuranRouteWithChildren = QuranRoute._addFileChildren(QuranRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  CalendarRoute: CalendarRoute,
  DuasRoute: DuasRoute,
  HadithRoute: HadithRoute,
  HajjRoute: HajjRoute,
  NamesRoute: NamesRoute,
  PillarsRoute: PillarsRoute,
  PrayerTimesRoute: PrayerTimesRoute,
  QiblaRoute: QiblaRoute,
  QuranRoute: QuranRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
